version: '2.1'
services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  db:
    build: ./webmysql
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor

  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     depends_on:
       - db
     ports:
       - 8765:80